name: Container Security Scan

on:
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bank-app:test .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bank-app:test
          severity: HIGH,CRITICAL
          exit-code: 1
